### PR TITLE
wip-scala-doc-fixes-proposal

### PR DESCRIPTION
**Pull request by k33g**
- add quotes to avoid sbt exceptions (core)
- add sbt section about dependencies (web)

### CODE REVIEW

**Comment by cescoffier** [comment]
Hello @k33g, 

Can you fix https://github.com/vert-x3/vertx-lang-scala/blob/master/vertx-lang-scala/src/main/docoverride/docoverride/dependencies/package-info.java

The files you modified are _generated_ at compile time.

**Comment by k33g** [comment]
@cescoffier  what about the 2nd file ?

**Comment by cescoffier** [comment]
`index.adoc` is generated from automatically from the Vert.x core doc.

**Comment by k33g** [comment]
@cescoffier ok, I'm not sure I understand the 2nd point, but I close this PR ans try a new one

**Pull request closed without merging**
